"""Write src/data/climate.ts from raw.json (see fetch.py)."""
import json, os

S = os.path.dirname(os.path.abspath(__file__))
raw = json.load(open(S + '/raw.json'))
years = sorted({tuple(v['years']) for v in raw.values()})
lines = [
    '// Generated by scripts/climate/build.py — do not edit by hand.',
    '// Monthly means from Open-Meteo historical weather data (ERA5 reanalysis, CC BY 4.0).',
    f"export const CLIMATE_YEARS = '{years[0][0]}–{years[-1][1]}'",
    '',
    '/** City id → [average daily high °C, average daily low °C, days with ≥1 mm of rain], January first. */',
    'export const CLIMATE: Record<string, [number[], number[], number[]]> = {',
]
for cid, v in raw.items():
    lines.append(f"  '{cid}': [{json.dumps(v['hi'])}, {json.dumps(v['lo'])}, {json.dumps(v['wet'])}],")
lines.append('}')
open(S + '/../../src/data/climate.ts', 'w').write('\n'.join(lines) + '\n')
print(len(raw), 'cities')
